Testing rspec
gscarv13/TicTacToe pull request #2
Opened 2021-01-15 21:35 UTC by gscarv13

asd

2021-01-16 02:57 UTC, MarilenaRoque requested changes
Hello Micronauts! :rocket:

Good job on your work on that project, so far! :clap:

However, there are a few necessary changes to complete all the requirements.

## Changes Required ♻️ 

- [ ] Use one it block for each expected behavior. Do not test multiple aspects in one it block.

Kindly, wrap each <expect> scenario in one <it> block.

- [ ] Add specs for all public methods you created in Tic Tac Toe project.

Please, add tests for the #change_box method to cover all the public methods.

Kindly check my comments below for more details and the [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/) to check the requirements listed.

Additional kudos on the separation of concerns in your methods. 😄 

Happy Coding!!! 💻 

**_Marilena Roque
Full-Stack Developer
Code Reviewer at Microverse Inc.
[Portfolio](https://mariroqueproject.com/) | [Linkedin](https://www.linkedin.com/in/roquemarilena/) 
marilenas@id.uf.br_**

2021-01-16 02:57 UTC, MarilenaRoque commented on spec/game_logic_spec.rb
> +      expect(board.check_input(5)).to be true
- Separate each expect in one it block

2021-01-16 02:57 UTC, MarilenaRoque commented on spec/game_logic_spec.rb
> +  draw.change_box('5', player2)
- Build tests to check the behavior of that function

2021-01-18 15:24 UTC, pipe2442 commented
Thanks, @MarilenaRoque all the changes were implemented. 😄

2021-01-18 16:01 UTC, Georjane requested changes
## Status: Changes Required 🛑 🔧 
### Hi there Team ✋🏽 
Very nice work you have done with the rspec testing. You have implemented all changes required by the previous Code Reviewer. It's a thumbs up for me. 👍🏽 

- [x] However, kindly add instructions for testing to your Readme file to get this project approved.

_Feel free to reach out to me on Slack if you have any questions, Witah Georjane_ 🤝 
Good luck on your project and Happy Coding 💻 

**Witah Georjane
Code Reviewer at Microverse Inc
[portfolio](https://witahgeorjane.tech/) | [linkedIn](https://www.linkedin.com/in/witah-georjane/)**

2021-01-18 21:20 UTC, teekaytech approved these changes
### Status: Approved :green_circle: 

**Congratulations team, this project has passed all the mandatory requirements. It is therefore approved :heavy_check_mark:**

Again, congratulations, you can merge to the default branch.
Good luck with your next project.

* * * 
**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

2021-01-18 21:25 UTC, merged